### ISSUE TITLE
Generalize Cosmo Store

### ISSUE THREAD

**Issue by kunjee17** [Dzoukr/CosmoStore#10]
@Dzoukr Loved your work. Is it possible abstract away the implementation to make is more generalize. 

I was trying Marten Event Store but it was tied with C# thingy for project part of it. But Marten as store is wonderful. 

And then there is lite db for simple testing or simple application. I am noob at ES so can't say how complicated it would be. But it would be good to have it.

**Comment by Dzoukr** [comment]
Hi Kunjal,
thanks a lot! If I got it right, you would like to have something like `CosmoStore.Facade` or `CosmoStore.Interface` and having Azure Table Storage & Cosmos DB as let say implementation of this? Then there can be other parts like `CosmoStore.Marten`, `CosmoStore.MongoDB`, and so on... Is it correct?

**Comment by kunjee17** [comment]
@Dzoukr yup... Very much correct.

**Comment by Dzoukr** [comment]
Funny... I'll need MongoDB version most likely pretty soon and was thinking about the same. It would mean to break and existing setup a little bit (TableStorage and CosmosDB would go into separated nuggets), but on the other hand since I follow the semver, it should be doable for next major version.

**Comment by kunjee17** [comment]
When you are planning to have next version? 

Side note: Don't use mongo db, if it is not forced by client.

**Comment by kunjee17** [comment]
Btw Maxime is having set up to push multiple nugets https://github.com/Fulma/Fulma/blob/master/build.fsx

**Comment by kunjee17** [comment]
And these you might find interesting https://github.com/TheAngryByrd/Marten.FSharp and https://github.com/Zaid-Ajaj/LiteDB.FSharp :)

**Comment by Dzoukr** [comment]
Not before start of March, sorry.

**Comment by kunjee17** [comment]
Oh no need for sorry. I was just asking out of curiosity. And if you require any help the please do let me know... Happy to help in whatever way possible.

**Comment by Odonno** [comment]
Maybe more `CosmoStore.Core` instead of `Facade` or `Interface`, don't you think? So, you will reuse core logic with each database API (inside each package).

**Comment by Dzoukr** [comment]
FYI, I already did some work in master, but want to have version 2 with new functionality (tracking by correlationId + adding causationId), so it is gonna be probably during March.

Expected architecture:
- CosmoStore (basic definition how ES should look like) - separated Nuget
- CosmoStore.CosmosDb (Cosmos implementation) - separated Nuget
- CosmoStore.TableStorage (Table Storage implementation) - separated Nuget

**Comment by kunjee17** [comment]
@Dzoukr I have no idea about those two ids. But again thanks for support and I don't mind waiting. 

> One suggestion if you don't mind. Create a v2 issues and announce in community for contribution. It might help you to go faster.

Fulma is too damn big library. I created GreenPrint similar way. Maxime is crazy good person when it comes to throw code out of windows but still having good guideline for contribution and separated issues which people can pick will always going to help.

**Comment by kunjee17** [comment]
BTW separated nuget is really good idea. You can have something like `CosmoStore.Core` as well. I am not big fan any naming convention though. But it will surely allow community to come up with different ES store implementation based on Core definitions.

> Don't want to increase your burden but shouldn't the name be changed? Cosmo is based on ConsmoDB and now it would be generalize.

**Comment by Odonno** [comment]
I agree. The name `CosmoStore` is too close to the implemented `CosmosDb` database but in the same time I really like the name `CosmoStore`.

**Comment by Dzoukr** [comment]
I'll most likely keep the CosmoStore name. It _may_ sounds similar to Cosmos DB, but I'd to keep some continuity + I like the name. :)

**Comment by kunjee17** [comment]
I also like the name. But again it is very near to ConsoDB. Let's do one thing. Make is more famous than ConsoDB. :P . That way they might need to change a name.

**Comment by Dzoukr** [comment]
Just release beta versions of v2.

Each CosmoStore implementation will be in separate package where `CosmoStore` is only API definition.

* https://www.nuget.org/packages/CosmoStore/2.0.0-beta1
* https://www.nuget.org/packages/CosmoStore.TableStorage/2.0.0-beta1
* https://www.nuget.org/packages/CosmoStore.CosmosDb/2.0.0-beta1

Please check it (I will do the same) and will release full version probably this week. :)

**Comment by Dzoukr** [comment]
Proper v2 release now public. Thanks for hint! 🙏
