### ISSUE TITLE
Collection name cannot be specified?

### ISSUE THREAD

**Issue by deyanp** [Dzoukr/CosmoStore#25]
Hi,

I am looking into creating a Cosmos DB database with shared throughput across all collections/containers. It seems the database name can be specified when setting up the configuration, but the collection/container name not? Asking because I wanted to create several XxxEvents collections, and have different Cosmos Db Triggers assigned to each one ..

**Comment by deyanp** [comment]
I see that another attribute can easily be added to CosmoStore.CosmosDb.Configuration, and used in CosmoStore.CosmosDb.EventStore.

But I see in the js sproc hardcoded Events, any idea how that can be changed?

**Comment by Dzoukr** [comment]
Hi @deyanp,

you are right, currently it cannot be changed, but I got an idea how to put more separate collections into one database. I'll keep it open until solved.

**Comment by Dzoukr** [comment]
Fixed in v2.1.0

**Comment by deyanp** [comment]
Thanks a lot, @Dzoukr!!!
