### ISSUE TITLE
Version 3 discussion

### ISSUE THREAD

**Issue by Dzoukr** [Dzoukr/CosmoStore#27]
This issue is created to track discussion about upcoming version 3 of CosmoStore and what should be its main goal. For me it is mainly about making EventStore "JSON payload representation agnostic" (in other words, do not force to use `JToken`) since Microsoft itself annonced new JSON API and moving away from Newtonsoft.Json coupling it its libraries. It will also allow to add other stores like LiteDB without unnecessary transformation to JToken and back.

Technically it should be quite easy to make `EventWrite`, `EventRead` and `EventStore` generic like:

```fsharp
type EventWrite<'a> = {
    Id : Guid
    CorrelationId : Guid option
    CausationId : Guid option
    Name : string
    Data : 'a
    Metadata : 'a option
}
```

Also upgrading existing libraries should be straightforward, so version 3 could be done pretty quickly.

Any other ideas? cc: @kunjee17 @ctaggart @TheAngryByrd @viktorvan

**Comment by Odonno** [comment]
@Dzoukr Should it be bound to .NET Core 3? Not sure if .NET Standard 3 is a thing.

**Comment by kunjee17** [comment]
Need and interface to implement json serialization. With default implementation provided by us. 

Also, we need some common mechanism in which all other implementation follows. Common functions etc. So, things are stay in line.

**Comment by Dzoukr** [comment]
> Should it be bound to .NET Core 3? Not sure if .NET Standard 3 is a thing.

Not sure neither :) Probably staying with Standard 2.0 is good idea.

> Need and interface to implement json serialization. With default implementation provided by us.

I don't think we need that on CosmoStore level (just API). Isn't it something that should be covered on storage implementation level? Of course each library needs to provide info what payload type `'a` it supports.

**Comment by kunjee17** [comment]
@dzoukr it is basically question of choice. If it is at implementation level then it will tie that implementation to json serialization. Nothing wrong in it. As in most case it is OK. But if someone like to play n plug thing then it would be difficult. 

That's why I told can have interface and default implementation for each store. Now, lite db don't allow replacing to that option will stay as it is. But Marten allows it. So, that can be updated. 

Simple dumb way would be 'a is string always. Because events will be serializable always. 

Again , these are suggestions. I can't foresee all the options with possible solutions as of now. But whatever flexibility we can put it would be great.

**Comment by bartelink** [comment]
The interfaces and design the [TypeShape `UnionContractEncoder` uses](https://eiriktsarpalis.wordpress.com/2018/10/30/a-contract-pattern-for-schemaless-datastores/) works well IMO as a way of doing serializer agnostic work. (See Equinox.Codec)

On the Cosmos side, it's also worth considering using the `Azure.Cosmos` [v3] SDK at some point given its pretty close to becoming the main/only properly maintained client lib.

**Comment by Dzoukr** [comment]
Thank you all for ideas and suggestions. I'll create new branch for version 3 and see where it goes. 😁

**Comment by TheAngryByrd** [comment]
> For me it is mainly about making EventStore "JSON payload representation agnostic" (in other words, do not force to use JToken) since Microsoft itself annonced new JSON API and moving away from Newtonsoft.Json coupling it its libraries

Overall I do like the idea of making it generic.  Allows the implementor to use whatever JSON library fits best.

> Simple dumb way would be 'a is string always. Because events will be serializable always.

The only issue with this is if people save giant documents you could end up putting lots in the [Large Object Heap](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/large-object-heap#how-an-object-ends-up-on-the-large-object-heap-and-how-gc-handles-them) quite easily, cause fragmentation, and users would need to set LargeObjectHeapCompactionMode in some regular timer.

```fsharp
    let setupLOHCollectionTimer () =
      let timeDelay = TimeSpan.FromMinutes 20.
      let timer = new Timers.Timer(timeDelay.TotalMilliseconds, AutoReset = true, Enabled = true)
      timer.Elapsed.Add(fun _ ->
        Runtime.GCSettings.LargeObjectHeapCompactionMode <- Runtime.GCLargeObjectHeapCompactionMode.CompactOnce
        GC.Collect()
      )
      timer
```

**Comment by TheAngryByrd** [comment]
While we're discussing breaking changes, I've been playing with [Redis Streams](https://redis.io/topics/streams-intro) and was thinking of also making an implementation for CosmoStore. The one issue I ran into was Position is tied to an `int64`.  Redis Streams uses a composite key `<millisecondsTime>-<sequenceNumber>` which has it's own semantics when it comes to incrementing.  So in a similar fashion we might want to generic the Position like:

```
type ExpectedPosition<'Position> =
    | Any
    | NoStream
    | Exact of 'Position

type EventsReadRange<'Position> =
    | AllEvents
    | FromPosition of 'Position
    | ToPosition of 'Position
    | PositionRange of fromPosition:'Position * toPosition:'Position

type Stream<'Position> = {
    Id : string
    LastPosition : 'Position
    LastUpdatedUtc: DateTime
}
```

This is the only store I know that acts like this for its event positions.

**Comment by deyanp** [comment]
What about implementation for MongoDB? I might need to move from Cosmos DB to MongoDB due to Cosmos' expensive storage (no compression), so I could write something ...

**Comment by Dzoukr** [comment]
@TheAngryByrd I like the idea of Position being generic type! Thanks for that!

**Comment by kunjee17** [comment]
@Dzoukr as we are discussing v3. One more minor change. There are too many string as id. So, it would be great if we will type alias so it would be great in intellisense when calling functions.

**Comment by Dzoukr** [comment]
Are you referring to `Stream` type?

The type alias is fine, maybe we could also think about single case union `type StreamId = StreamId of string`?

**Comment by kunjee17** [comment]
@Dzoukr yup. Similar stuff.

**Comment by kunjee17** [comment]
@Dzoukr any status for others data store. It should technically work for everyone.

**Comment by bartelink** [comment]
FYI https://github.com/jet/FsCodec has been split out of Equinox - might make sense to support it as a way of generating messages (though I can appreciate you wanting to stay dependency free)?

Also regarding streamId, `type Target = AggregateId of category: string * id: string | StreamName of streamName: string` can work well [like this](https://github.com/jet/dotnet-templates/blob/master/equinox-web/Domain/Todo.fs#L76) - lets you keep a strongly typed sub-id with FSharp.UMX and then encapsulate adding the categoryId (which you then use as a constant when [parsing on the projection side](https://github.com/jet/dotnet-templates/blob/master/propulsion-summary-consumer/Infrastructure.fs#L19))

**Comment by bartelink** [comment]
You'll also never get a better time to rename all Cosmos `Collection` terms to `Container` - the portal and all docs now exclusively refer to Containers.

**Comment by Dzoukr** [comment]
Hi @kunjee17, the Cosmos and TableStorage rewrite is done. I'll do the InMemory soon and then I was thinking to hand it over to you to resolve Postgres 😄 

Hi @bartelink , yes, Collection is no more, now Container is used (new version is based on SDK v3, which has btw totally changed). Regarding the Stream type... I may not fully understand what is the meaning of `AggregateId of category: string * id: string` - is it another way how to generate string identifier of Stream?

**Comment by Dzoukr** [comment]
@kunjee17 Cosmos, TableStorage & InMemory are now fully converted. Should I do also the Marten one, or leave it up to you?

**Comment by kunjee17** [comment]
@Dzoukr as you wish. It should not be issue but if you like I can do it by next week. It depends how much you are in Zen to convert and how much delay is OK for you.

**Comment by Dzoukr** [comment]
This issue is 2 months old 😄 I am not in hurry. If I will find time earlier, I can do it, but I am pretty sure it won't happen due my work duties.

**Comment by kunjee17** [comment]
@Dzoukr I will have a look. BTW as position is now not int64. So, now we need to abstract things there too. I will have a look. Mostly next week.

**Comment by Dzoukr** [comment]
The position is now generic parameter, so it is up to each implementation what to use. Thanks again @TheAngryByrd for good idea about that.

**Comment by kunjee17** [comment]
@Dzoukr why we are having this? https://github.com/Dzoukr/CosmoStore/blob/version3/src/CosmoStore/Validation.fs . I actually forgot about it. This doesn't mean just add  at end of stream. Because specific position is not end of stream we give error and no stream is also not end of stream (for new stream so it is start of stream) we give error.

**Comment by Dzoukr** [comment]
@kunjee17 This is for optimistic concurrency. You start indexing each stream from number one. This function validates that index (position) you are going to write is same as expected.

**Comment by bartelink** [comment]
I guess its too late to start it from `0` ? EventStore, arrays and all that's good starts from there doesn't it ? ;)

**Comment by Dzoukr** [comment]
I am not against it, but that would be real breaking change (now version 3 seems pretty smooth update from v2). I initally thought to use `0` as start, but realized having it from `1` I can use the same number as information about number of existing events on stream level without any additional (even simplest) calculation. 🤔 Don't know, really. We can do it, we can leave it as it is...

**Comment by bartelink** [comment]
I agree its too late to do a breaking change and would put this sidenote-comment on gitter if you had one ;)

My point is that this doesnt align with EventStore and SqlStreamStore - I personally had an abstraction one-based at one point but realised in time: one-based in practice is actually agonising to work with because it doesnt align with [typically zero based]array indexing.

On the plus side, you're in alignment with VB (the one before VB.NET) ;)

**Comment by bartelink** [comment]
Taking a different angle - the 1 based value makes a lot of sense if you term it a `Version` - i.e. `Version 1` being when there is one event at `Position 0`. So all you need to do is rename. Such a naming scheme also makes `expectedVersion` finally make sense; the representation in EventStore etc is such that ExpectedVersion when writing the first event is 'version' 0. You can then say that a Position is an index into the virtual 0-based array at which one is about to write, and a Version is the number of events you have. Then you use the [1 based] Version as the [0 based] Position for the next write and you're  adding or subtracting in less cases.

**Comment by Dzoukr** [comment]
@bartelink dammit, you really made me think :))) I kind of like it to rename `Position` to `Version` and keep indexing from `1`. The only concern here is backward compatibility. I need to think about fact, that for older events the term `Position` is used, but luckily CosmosDB and TableStorage are both schemaless, so it should be possible to handle on query side when reading events back. What do you think @kunjee17? Any blocker on your side with that? I really feel it's true as Ruben said: "It will together finally make sense." Since we are touching more things (like making it more generic), this could be good change.

**Comment by kunjee17** [comment]
@Dzoukr We are still in schema less land in every implementation. I can't foresee any blocker.

**Comment by Dzoukr** [comment]
Latest update: I went through all the code for CosmosDB and TableStorage and renaming `Position` to `Version` is true breaking change. Events container is created with unique keys combination (`streamId` & `position`), which would make it difficult to change "on the fly" (not sure if even possible). Reading existing events (written in old manner) is ok, but this one is hard.

So really thinking if it is worth it. Any existing store from v1 and v2 cannot be used for working with v3. 🤔 Not without some kind of migration tool...

??? any thoughts?

**Comment by TheAngryByrd** [comment]
This is always the downside to writing something that persists data, the data migration strategy 😿 

I personally wouldn't want to make a breaking change without having a data migration strategy for each persistence method, _unless_ we know 100% for sure no one is using this is a production environment. 

Another method is to inspect the underlying data at read time, figure out if we can deserialize to the v1/v2 format, then try to "upgrade" to the v3 format.

**Comment by bartelink** [comment]
One loses a lot by introducing the complexity of up/downconversion paths with associated tests. Can you do all the renames but leave a "using old label for backcompat" comment? If that halfway house is too much of a mess, I'd say the choice is obvious - leave it as it is; and there existing name is not without its positives

**Comment by kunjee17** [comment]
If there are too many breaking changes then we can keep the v2 alive with v3 migration set up. Normally every library has to pass through this. I guess this library reach that point very early.

**Comment by Dzoukr** [comment]
Thanks all for comments, I now think I know how to handle backward compat... Need to test it first, but it looks promising now.

**Comment by Dzoukr** [comment]
Thanks all for feedback, just released v3 with all the changes. Table Storage & CosmosDB are both backward compatible 🎉 
Please, @kunjee17, if you would find time to adjust Marten library to the latest version, let me know.
Thanks again everyone involved!

**Comment by kunjee17** [comment]
@Dzoukr was out for a week. Just came back. I ll have a look at other implementation of the same.

**Comment by kunjee17** [comment]
@Dzoukr code is in master or should I branch out from Version3 branch ?

**Comment by Dzoukr** [comment]
@kunjee17 Version3 is deleted - please use `master`
