### ISSUE TITLE
Confusion in types. Might need some extra functions.

### ISSUE THREAD

**Issue by kunjee17** [Dzoukr/CosmoStore#32]
Even though we are providing more generic types to make things more flexible. In code we are still having `JToken` and `int64`. 

Obviously we are doing logic part on it. We might need to update that, to truly support everything.

**Comment by Dzoukr** [comment]
I don't understand what do you mean by that. `Newtonsoft.Json` with `int64` are used only on each implementation level - each storage provider (Cosmos, TableStorage, InMemory) decides what storage and version it use. Interface for `CosmoStore` is now fully generic and ready to be implemented by anyone.

**Comment by kunjee17** [comment]
@Dzoukr interface is great. Almost perfect. I was thinking of removing implementation level all together. At least for few implementation. 

So, thinking of providing functions with default implementation  in Config. So, that logic can be provided by user if user likes to change things. 

Like if user wants to change JsonSerializer for Marten, he / she should be able to change it. So, I was thinking in that direction.

**Comment by Dzoukr** [comment]
Oh, now I see. That would mean we need to have possibility to plugin various de/serializers into implementation, but why not?

**Comment by kunjee17** [comment]
Exactly. As we provide more and more support, I think we should not bind end user for serialization or version check (it can be int64 or it can be any thing ). What you say? Should we start pushing Cosmo store to new Cosmos?

**Comment by Dzoukr** [comment]
I think we can create new version of `CosmoStore.Cosmos` package with default (newtonsoft?) serialization + possibility push custom serializer over configuration.

**Comment by kunjee17** [comment]
We can close this issue. As not JToken is there for tests only.
