### ISSUE TITLE
There is some Dependancy issues 

### ISSUE THREAD

**Issue by kunjee17** [Dzoukr/CosmoStore#40]
I was trying pull CosmoStore.ServiceStack. It should depend on CosmoStore 3.0 but it is depending on CosmoStore 3.0.1. And that is making paket little crazy. 

Can you please cross check. I guess some thing messed up at the time of publishing.

**Comment by Dzoukr** [comment]
Ufff, had to change how to create/publish Nuget, but should be fixed now. Thanks for spotting! 👍
