### ISSUE TITLE
Missing Version in CosmoStore 3.0?

### ISSUE THREAD

**Issue by brase** [Dzoukr/CosmoStore#41]
I tried CosmoStore.LiteDb today and had a weird experiance. 

I installed it with paket. When running it I got a runtime error about the missing Dll CosmoStore in Version 3.0.0.0

I then opened the CosmoStore.dll which comes with the nuget package in dnspy where it shows it has version 1.0.0.0. I changed this to 3.0.0.0 so that I got rid of the runtime error.

For me it looks like the release 3.0 is faulty but I am absolutly not sure about this, because it is already 4 months old. Am I really the first one who encountered this issue?

**Comment by Dzoukr** [comment]
That's strange. I'll look at it, maybe it's connected with #40? @kunjee17 any issue using LiteDb on your side?

**Comment by kunjee17** [comment]
@Dzoukr  this must be same issue as we faced in Servicestack package. If It couldn't find version 3.0.0.1 or something it fall back to 1.0 . Which obviously will not work.

**Comment by Dzoukr** [comment]
Well, that's really weird, but I was able to reproduce the problem. Just republished all packages for sure and will re-test after all new versions indexed on Nuget feed. But wondering what was the root of whole issue? Not using `Version` and using `PackageVersion` instead in old publishing setup? 🤔

**Comment by bartelink** [comment]
I'd just switch to using [MinVer](https://github.com/adamralph/minver) and be done with it - example: https://github.com/jet/FsCodec/tree/master/src/FsCodec

**Comment by Dzoukr** [comment]
Thanks @bartelink , nice hint - I'll look at it!
Thanks @brase for reporting issue - it seems to be fixed now using the latest version. Please, can you check a confirm / close issue?

**Comment by brase** [comment]
I can confirm. It's working now. Thank you!

**Comment by Dzoukr** [comment]
I thank YOU, @brase!
