### ISSUE TITLE
Observing appended events on distributed systems

### ISSUE THREAD

**Issue by Swoorup** [Dzoukr/CosmoStore#48]
Is there a mechanism to observe appended events from different server instances using the libray?

**Comment by Dzoukr** [comment]
I would for such case Queue (Azure Table Storage Queue or Service Bus) or Topic.

**Comment by Swoorup** [comment]
There are some concerns regarding handling out of order messages, global ordering of events. Wondering would that be a part of this library in the future?

**Comment by Dzoukr** [comment]
Hmmm. 🤔 Most likely not in near future. I think making these events observable as they are processed in store itself should be sufficient for most of scenarios. Of course, if you are on Cosmos DB, you can use change feed functionality, but not sure how is it with ordering of events.

**Comment by Swoorup** [comment]
Cool thanks for letting know, I think this feature is critical for distributed applications or read instances in CQRS. I know SQLStreamStore has support for it, which I assume uses polling. Currently I use combination of redis streams for it and SQL for persistence.

**Comment by bartelink** [comment]
I guess this is blatant advertising but...

While the general process of deciding events to write, writing events, and doing (cached) reads is relatively generalisable... (see Equinox)

There are many more factors in play on the observing events... https://github.com/jet/propulsion's raison d'etre is exactly this - wrapping up the ways of doing such observations in appropriate ways. (The code originated in Equinox, but it quickly becomes apparent as you strt pulling on the thread that the concerns are different).

In general, Propulsion has minimal coupling to Equinox (PRs to completely decouple it are more than welcome)

If you want to discuss more, #equinox in the DDD-CQRS-ES slack is probably the best place.

The specific case of SqlStreamStore is unfortunately not yet covered, but would be a welcome addition:
- @rajivhost started https://github.com/jet/propulsion/pull/52, but I asked him to hold back as...
- @scrwtp has a simpler variant in the works (he's proving it in prod atm)...

**Comment by Dzoukr** [comment]
I guess we can close this now

**Comment by bartelink** [comment]
FWIW there's a generic SqlStreamStore projector that uses [`Propulsion.SqlStreamStore`](https://github.com/jet/propulsion/pull/72) in https://github.com/jet/dotnet-templates/pull/74 (the same `proProjector` template can consume from CosmosDB or EventStoreDB)

Happy to take PRs to Propulsion to enable tailing other sources...
